# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-31 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=200)),
                ('message', models.TextField(default='', max_length=1024)),
            ],
        ),
    ]
