# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-29 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='contact_message',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='contact_name',
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='test', max_length=200),
        ),
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(default='test', max_length=1024),
        ),
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(default='test', max_length=50),
        ),
    ]
