# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-09 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('polishes', 'Polishes'), ('care', 'Care')], default='polishes', max_length=11),
        ),
    ]
