# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-12 13:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200712_1118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
    ]
