# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-25 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200712_1310'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Polishes', 'Polishes'), ('Care', 'Care')], default='Polishes', max_length=11),
        ),
    ]
