# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-30 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20200730_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='Name', max_length=254),
        ),
    ]
