# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-30 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20200730_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default='price', max_digits=6),
        ),
    ]
